### ISSUE TITLE
Difficult to acquire uri from job ticket prior to completion

### ISSUE THREAD

**Issue by xloem** [freenet/pyFreenet#18]
There is no way to query if a ticket has an associated URI yet.  It is set on receipt by URIGenerated, but the only way to check for it would by catch the exception raised by `uri = job.uri` if it hasn't been set yet.

**Comment by ArneBab** [comment]
If you need that for a CHK uri, you can run a separate job to create the uri (look for chkOnly). However sharing an URI before the upload is complete makes it much easier for attackers to track down your identity (since they can use it to calculate the chunks you will upload). This is why normally the uri is only provided once an upload is finished.

**Comment by ArneBab** [comment]
See fcpupload to get the uri early.
